services:

  mongo-db:
    container_name: customer_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/customer_mongo_db:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    container_name: customer_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo-db:27017/
      ME_CONFIG_BASICAUTH: false
  
  product-pg-db-service:
    container_name: product_pg_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product
    ports:
      - 5433:5432
    volumes:
      - ./data/product_pg_db:/var/lib/postgresql/data
    networks:
        - bridgenetwork

  pgadmin-service:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: mahdighasri@gmail.com
        PGADMIN_DEFAULT_PASSWORD: imo754&%$
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      restart: unless-stopped
      volumes:
        - ./data/pgadmin:/var/lib/pgadmin
      ports:
        - "8092:80"
      depends_on: 
        - product-pg-db-service
      networks:
        - bridgenetwork

  order-mysql-db-service:
    container_name: order-mysql-db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: order
    ports:
      - 3306:3306
    volumes:
      - ./data/order-mysql-db:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - bridgenetwork
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - bridgenetwork

networks:
  bridgenetwork:
    driver: bridge
        