services:

  notification-mongo-db:
    container_name: notification_mongo_db
    image: mongo
    ports:
      - ${NOTIFICATION_DB_SERVICE_PORT}:27017
    volumes:
      - ./data/notification_mongo_db:/data/db
      - ./data/notification_mongo_db/configdb:/data/configdb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOTIFICATION_DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTIFICATION_DB_PASSWORD}

  notification-mongo-express:
    container_name: notification_mongo_express
    image: mongo-express
    restart: on-failure
    ports:
      - ${NOTIFICATION_MONGO_EXPRESS_PORT}:8081
    depends_on:
      - ${NOTIFICATION_DB_SERVICE_NAME}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${NOTIFICATION_MONGO_EXPRESS_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${NOTIFICATION_MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${NOTIFICATION_MONGO_EXPRESS_USER_NAME}:${NOTIFICATION_MONGO_EXPRESS_PASSWORD}@${NOTIFICATION_DB_SERVICE_NAME}:27017/
      ME_CONFIG_BASICAUTH: false
