server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
      change-log: classpath:/db/changelog-master.xml

